import type { FungalZone } from "./types";

function generateRainHistory(baseMm: number): FungalZone["rainHistory"] {
  const days: FungalZone["rainHistory"] = [];
  for (let i = 13; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    const variation = Math.sin(i * 0.8) * 8 + Math.cos(i * 1.3) * 3;
    days.push({
      date: date.toISOString().split("T")[0],
      mm: Math.max(0, Math.round((baseMm + variation) * 10) / 10),
    });
  }
  return days;
}

function generateHourlyForecasts(
  baseTemp: number,
  baseHumidity: number,
  baseSoil: number
): FungalZone["hourlyForecasts"] {
  const hours: FungalZone["hourlyForecasts"] = [];
  for (let h = 0; h < 24; h++) {
    const tempCycle = Math.sin(((h - 6) * Math.PI) / 12) * 6;
    const humidityCycle = Math.cos(((h - 5) * Math.PI) / 12) * 15;
    hours.push({
      hour: h,
      temperature: Math.round((baseTemp + tempCycle) * 10) / 10,
      humidity: Math.min(100, Math.max(40, Math.round(baseHumidity + humidityCycle))),
      soilMoisture: Math.min(100, Math.max(20, Math.round((baseSoil + humidityCycle * 0.3) * 10) / 10)),
    });
  }
  return hours;
}

export const FUNGAL_ZONES: FungalZone[] = [
  {
    id: "matese-bocca-selva-estatino",
    name: "Bocca della Selva — Radura Est",
    region: "matese",
    lat: 41.3521,
    lng: 14.4187,
    altitude: 820,
    exposure: "east",
    forestType: "Castagneto misto con Quercia cerro",
    species: ["estatino", "galletto"],
    rainHistory: generateRainHistory(12),
    baseSoilMoisture: 72,
    nightThermalShock: 11.5,
    parkingLat: 41.3489,
    parkingLng: 14.4123,
    hourlyForecasts: generateHourlyForecasts(14, 78, 72),
    collectionWindow: {
      startHour: 5,
      startMinute: 15,
      endHour: 9,
      endMinute: 0,
      label: "Dalle 05:15 alle 09:00 — prima del picco di calore",
    },
  },
  {
    id: "matese-bocca-selva-porcino",
    name: "Bocca della Selva — Faggeta Alta",
    region: "matese",
    lat: 41.3568,
    lng: 14.4215,
    altitude: 1180,
    exposure: "north",
    forestType: "Faggeta fitta d'altura",
    species: ["porcino"],
    rainHistory: generateRainHistory(18),
    baseSoilMoisture: 81,
    nightThermalShock: 14.2,
    parkingLat: 41.3489,
    parkingLng: 14.4123,
    hourlyForecasts: generateHourlyForecasts(11, 85, 81),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 30,
      label: "Dalle 06:00 alle 10:30 — umidità ottimale al mattino",
    },
  },
  {
    id: "matese-cusano-radura",
    name: "Cusano Mutri — Radura del Matese",
    region: "matese",
    lat: 41.4723,
    lng: 14.5089,
    altitude: 745,
    exposure: "east",
    forestType: "Castagneto da frutto con sottobosco muschioso",
    species: ["estatino", "galletto"],
    rainHistory: generateRainHistory(15),
    baseSoilMoisture: 68,
    nightThermalShock: 10.8,
    parkingLat: 41.4681,
    parkingLng: 14.5012,
    hourlyForecasts: generateHourlyForecasts(16, 74, 68),
    collectionWindow: {
      startHour: 5,
      startMinute: 30,
      endHour: 8,
      endMinute: 45,
      label: "Dalle 05:30 alle 08:45 — primo sole su esposizione Est",
    },
  },
  {
    id: "matese-cusano-fosso",
    name: "Cusano Mutri — Fosso del Vallone",
    region: "matese",
    lat: 41.4658,
    lng: 14.5142,
    altitude: 920,
    exposure: "north",
    forestType: "Fosso umido con muschi e Abeti bianchi",
    species: ["galletto"],
    rainHistory: generateRainHistory(22),
    baseSoilMoisture: 88,
    nightThermalShock: 9.5,
    parkingLat: 41.4681,
    parkingLng: 14.5012,
    hourlyForecasts: generateHourlyForecasts(12, 90, 88),
    collectionWindow: {
      startHour: 6,
      startMinute: 30,
      endHour: 11,
      endMinute: 0,
      label: "Dalle 06:30 alle 11:00 — ombra fitta mantiene umidità",
    },
  },
  {
    id: "matese-guardiaregia-porcino",
    name: "Guardiaregia — Cresta del Matese",
    region: "matese",
    lat: 41.4312,
    lng: 14.5523,
    altitude: 1245,
    exposure: "north",
    forestType: "Faggeta fitta d'altura con muschio epifita",
    species: ["porcino"],
    rainHistory: generateRainHistory(20),
    baseSoilMoisture: 84,
    nightThermalShock: 15.8,
    parkingLat: 41.4256,
    parkingLng: 14.5478,
    hourlyForecasts: generateHourlyForecasts(10, 87, 84),
    collectionWindow: {
      startHour: 5,
      startMinute: 45,
      endHour: 9,
      endMinute: 30,
      label: "Dalle 05:45 alle 09:30 — escursione termica notturna ideale",
    },
  },
  {
    id: "matese-guardiaregia-galletti",
    name: "Guardiaregia — Vallone del Calvario",
    region: "matese",
    lat: 41.4287,
    lng: 14.5589,
    altitude: 980,
    exposure: "north",
    forestType: "Fosso ombreggiato con muschi e Felci",
    species: ["galletto"],
    rainHistory: generateRainHistory(19),
    baseSoilMoisture: 86,
    nightThermalShock: 10.2,
    parkingLat: 41.4256,
    parkingLng: 14.5478,
    hourlyForecasts: generateHourlyForecasts(13, 89, 86),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 0,
      label: "Dalle 06:00 alle 10:00 — zona umida sotto chioma fitta",
    },
  },
  {
    id: "taburno-crest-estatino",
    name: "Taburno — Versante Est Camposauro",
    region: "taburno",
    lat: 41.0823,
    lng: 14.6512,
    altitude: 780,
    exposure: "east",
    forestType: "Querceto misto con Castagno",
    species: ["estatino"],
    rainHistory: generateRainHistory(11),
    baseSoilMoisture: 70,
    nightThermalShock: 12.1,
    parkingLat: 41.0789,
    parkingLng: 14.6445,
    hourlyForecasts: generateHourlyForecasts(15, 76, 70),
    collectionWindow: {
      startHour: 5,
      startMinute: 0,
      endHour: 8,
      endMinute: 30,
      label: "Dalle 05:00 alle 08:30 — sole mattutino su versante Est",
    },
  },
  {
    id: "taburno-vallone-galletti",
    name: "Taburno — Vallone delle Ginestre",
    region: "taburno",
    lat: 41.0756,
    lng: 14.6589,
    altitude: 890,
    exposure: "north",
    forestType: "Fosso muschioso con Acero e Faggio giovane",
    species: ["galletto", "estatino"],
    rainHistory: generateRainHistory(16),
    baseSoilMoisture: 79,
    nightThermalShock: 10.5,
    parkingLat: 41.0789,
    parkingLng: 14.6445,
    hourlyForecasts: generateHourlyForecasts(13, 82, 79),
    collectionWindow: {
      startHour: 6,
      startMinute: 15,
      endHour: 10,
      endMinute: 15,
      label: "Dalle 06:15 alle 10:15 — umidità costante nel fosso",
    },
  },
  {
    id: "taburno-cima-porcino",
    name: "Taburno — Cima Camposauro",
    region: "taburno",
    lat: 41.0689,
    lng: 14.6623,
    altitude: 1165,
    exposure: "north",
    forestType: "Faggeta fitta d'altura",
    species: ["porcino"],
    rainHistory: generateRainHistory(21),
    baseSoilMoisture: 83,
    nightThermalShock: 14.5,
    parkingLat: 41.0789,
    parkingLng: 14.6445,
    hourlyForecasts: generateHourlyForecasts(11, 86, 83),
    collectionWindow: {
      startHour: 5,
      startMinute: 30,
      endHour: 9,
      endMinute: 0,
      label: "Dalle 05:30 alle 09:00 — shock termico notturno >14°C",
    },
  },
  {
    id: "sannio-pietrelcina",
    name: "Sannio — Bosco di Pietrelcina",
    region: "sannio",
    lat: 41.0612,
    lng: 14.5289,
    altitude: 680,
    exposure: "east",
    forestType: "Castagneto con sottobosco di Quercia",
    species: ["estatino", "galletto"],
    rainHistory: generateRainHistory(10),
    baseSoilMoisture: 65,
    nightThermalShock: 9.8,
    parkingLat: 41.0589,
    parkingLng: 14.5234,
    hourlyForecasts: generateHourlyForecasts(17, 72, 65),
    collectionWindow: {
      startHour: 5,
      startMinute: 45,
      endHour: 9,
      endMinute: 15,
      label: "Dalle 05:45 alle 09:15 — radura esposta a Est",
    },
  },
  {
    id: "molise-matese-lago",
    name: "Molise — Versante Lago del Matese",
    region: "molise",
    lat: 41.3389,
    lng: 14.4012,
    altitude: 1010,
    exposure: "north",
    forestType: "Faggeta con zone umide lacustri",
    species: ["porcino", "galletto"],
    rainHistory: generateRainHistory(17),
    baseSoilMoisture: 82,
    nightThermalShock: 13.2,
    parkingLat: 41.3356,
    parkingLng: 14.3978,
    hourlyForecasts: generateHourlyForecasts(12, 84, 82),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 0,
      label: "Dalle 06:00 alle 10:00 — umidità dal lago e faggeta",
    },
  },
  {
    id: "campania-partenio",
    name: "Campania — Massiccio del Partenio",
    region: "campania",
    lat: 41.0123,
    lng: 14.7123,
    altitude: 1120,
    exposure: "north",
    forestType: "Faggeta fitta con Faggio e Acero",
    species: ["porcino"],
    rainHistory: generateRainHistory(19),
    baseSoilMoisture: 80,
    nightThermalShock: 13.8,
    parkingLat: 41.0089,
    parkingLng: 14.7056,
    hourlyForecasts: generateHourlyForecasts(11, 85, 80),
    collectionWindow: {
      startHour: 5,
      startMinute: 30,
      endHour: 9,
      endMinute: 30,
      label: "Dalle 05:30 alle 09:30 — quota >1100m, escursione termica forte",
    },
  },
];

export const MAP_CENTER = { lat: 41.28, lng: 14.52 };
export const MAP_DEFAULT_ZOOM = 11;
