import type { FungalZone } from "./types";
import {
  BENEVENTO,
  driveMinutesToKm,
  MAX_DRIVE_MINUTES_FROM_BENEVENTO,
} from "./benevento";
import { assertZonesValid } from "./zoneCoordinateService";

type ZoneInput = Omit<
  FungalZone,
  "driveMinutesFromBenevento" | "kmFromBenevento"
>;

/** Tempi di percorrenza stimati da Benevento città (strade, non in linea d'aria) */
const DRIVE_FROM_BENEVENTO: Record<string, number> = {
  "matese-bocca-selva-estatino": 65,
  "matese-bocca-selva-porcino": 65,
  "matese-cusano-radura": 72,
  "matese-cusano-fosso": 72,
  "matese-guardiaregia-porcino": 78,
  "matese-guardiaregia-galletti": 78,
  "taburno-crest-estatino": 42,
  "taburno-vallone-galletti": 42,
  "taburno-cima-porcino": 48,
  "sannio-pietrelcina": 28,
  "sannio-telese": 35,
  "sannio-foce-sannita": 48,
  "sannio-pietraroja": 82,
  "sannio-cerreto": 52,
  "molise-matese-lago": 70,
  "molise-trivento": 58,
  "molise-bojano": 62,
  "molise-colle-anchise": 68,
  "molise-campobasso": 72,
  "campania-partenio": 88,
  "campania-laceno": 118,
  "campania-summonte": 78,
  "campania-cervati": 142,
  "basilicata-pollino-san-severino": 148,
  "basilicata-gallipoli-cognato": 112,
  "basilicata-vulture": 98,
  "basilicata-monticchio": 96,
  "basilicata-lagonegrese": 168,
};

function generateRainHistory(baseMm: number): FungalZone["rainHistory"] {
  const days: FungalZone["rainHistory"] = [];
  for (let i = 13; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    const variation = Math.sin(i * 0.8) * 8 + Math.cos(i * 1.3) * 3;
    days.push({
      date: date.toISOString().split("T")[0],
      mm: Math.max(0, Math.round((baseMm + variation) * 10) / 10),
    });
  }
  return days;
}

function generateHourlyForecasts(
  baseTemp: number,
  baseHumidity: number,
  baseSoil: number
): FungalZone["hourlyForecasts"] {
  const hours: FungalZone["hourlyForecasts"] = [];
  for (let h = 0; h < 24; h++) {
    const tempCycle = Math.sin(((h - 6) * Math.PI) / 12) * 6;
    const humidityCycle = Math.cos(((h - 5) * Math.PI) / 12) * 15;
    hours.push({
      hour: h,
      temperature: Math.round((baseTemp + tempCycle) * 10) / 10,
      humidity: Math.min(100, Math.max(40, Math.round(baseHumidity + humidityCycle))),
      soilMoisture: Math.min(100, Math.max(20, Math.round((baseSoil + humidityCycle * 0.3) * 10) / 10)),
    });
  }
  return hours;
}

const RAW_FUNGAL_ZONES: ZoneInput[] = [
  {
    id: "matese-bocca-selva-estatino",
    name: "Bocca della Selva — Radura Est",
    region: "matese",
    lat: 41.3521,
    lng: 14.4187,
    altitude: 820,
    exposure: "east",
    forestType: "Castagneto misto con Quercia cerro",
    species: ["estatino", "galletto"],
    rainHistory: generateRainHistory(12),
    baseSoilMoisture: 72,
    nightThermalShock: 11.5,
    parkingLat: 41.3489,
    parkingLng: 14.4123,
    hourlyForecasts: generateHourlyForecasts(14, 78, 72),
    collectionWindow: {
      startHour: 5,
      startMinute: 15,
      endHour: 9,
      endMinute: 0,
      label: "Dalle 05:15 alle 09:00 — prima del picco di calore",
    },
  },
  {
    id: "matese-bocca-selva-porcino",
    name: "Bocca della Selva — Faggeta Alta",
    region: "matese",
    lat: 41.3568,
    lng: 14.4215,
    altitude: 1180,
    exposure: "north",
    forestType: "Faggeta fitta d'altura",
    species: ["porcino"],
    rainHistory: generateRainHistory(18),
    baseSoilMoisture: 81,
    nightThermalShock: 14.2,
    parkingLat: 41.3489,
    parkingLng: 14.4123,
    hourlyForecasts: generateHourlyForecasts(11, 85, 81),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 30,
      label: "Dalle 06:00 alle 10:30 — umidità ottimale al mattino",
    },
  },
  {
    id: "matese-cusano-radura",
    name: "Cusano Mutri — Radura del Matese",
    region: "matese",
    lat: 41.4723,
    lng: 14.5089,
    altitude: 745,
    exposure: "east",
    forestType: "Castagneto da frutto con sottobosco muschioso",
    species: ["estatino", "galletto"],
    rainHistory: generateRainHistory(15),
    baseSoilMoisture: 68,
    nightThermalShock: 10.8,
    parkingLat: 41.4681,
    parkingLng: 14.5012,
    hourlyForecasts: generateHourlyForecasts(16, 74, 68),
    collectionWindow: {
      startHour: 5,
      startMinute: 30,
      endHour: 8,
      endMinute: 45,
      label: "Dalle 05:30 alle 08:45 — primo sole su esposizione Est",
    },
  },
  {
    id: "matese-cusano-fosso",
    name: "Cusano Mutri — Fosso del Vallone",
    region: "matese",
    lat: 41.4658,
    lng: 14.5142,
    altitude: 920,
    exposure: "north",
    forestType: "Fosso umido con muschi e Abeti bianchi",
    species: ["galletto"],
    rainHistory: generateRainHistory(22),
    baseSoilMoisture: 88,
    nightThermalShock: 9.5,
    parkingLat: 41.4681,
    parkingLng: 14.5012,
    hourlyForecasts: generateHourlyForecasts(12, 90, 88),
    collectionWindow: {
      startHour: 6,
      startMinute: 30,
      endHour: 11,
      endMinute: 0,
      label: "Dalle 06:30 alle 11:00 — ombra fitta mantiene umidità",
    },
  },
  {
    id: "matese-guardiaregia-porcino",
    name: "Guardiaregia — Cresta del Matese",
    region: "matese",
    lat: 41.4312,
    lng: 14.5523,
    altitude: 1245,
    exposure: "north",
    forestType: "Faggeta fitta d'altura con muschio epifita",
    species: ["porcino"],
    rainHistory: generateRainHistory(20),
    baseSoilMoisture: 84,
    nightThermalShock: 15.8,
    parkingLat: 41.4256,
    parkingLng: 14.5478,
    hourlyForecasts: generateHourlyForecasts(10, 87, 84),
    collectionWindow: {
      startHour: 5,
      startMinute: 45,
      endHour: 9,
      endMinute: 30,
      label: "Dalle 05:45 alle 09:30 — escursione termica notturna ideale",
    },
  },
  {
    id: "matese-guardiaregia-galletti",
    name: "Guardiaregia — Vallone del Calvario",
    region: "matese",
    lat: 41.4287,
    lng: 14.5589,
    altitude: 980,
    exposure: "north",
    forestType: "Fosso ombreggiato con muschi e Felci",
    species: ["galletto"],
    rainHistory: generateRainHistory(19),
    baseSoilMoisture: 86,
    nightThermalShock: 10.2,
    parkingLat: 41.4256,
    parkingLng: 14.5478,
    hourlyForecasts: generateHourlyForecasts(13, 89, 86),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 0,
      label: "Dalle 06:00 alle 10:00 — zona umida sotto chioma fitta",
    },
  },
  {
    id: "taburno-crest-estatino",
    name: "Taburno — Versante Est Camposauro",
    region: "taburno",
    lat: 41.0823,
    lng: 14.6512,
    altitude: 780,
    exposure: "east",
    forestType: "Querceto misto con Castagno",
    species: ["estatino"],
    rainHistory: generateRainHistory(11),
    baseSoilMoisture: 70,
    nightThermalShock: 12.1,
    parkingLat: 41.0718,
    parkingLng: 14.6654,
    hourlyForecasts: generateHourlyForecasts(15, 76, 70),
    collectionWindow: {
      startHour: 5,
      startMinute: 0,
      endHour: 8,
      endMinute: 30,
      label: "Dalle 05:00 alle 08:30 — sole mattutino su versante Est",
    },
  },
  {
    id: "taburno-vallone-galletti",
    name: "Taburno — Vallone delle Ginestre",
    region: "taburno",
    lat: 41.0756,
    lng: 14.6589,
    altitude: 890,
    exposure: "north",
    forestType: "Fosso muschioso con Acero e Faggio giovane",
    species: ["galletto", "estatino"],
    rainHistory: generateRainHistory(16),
    baseSoilMoisture: 79,
    nightThermalShock: 10.5,
    parkingLat: 41.0718,
    parkingLng: 14.6654,
    hourlyForecasts: generateHourlyForecasts(13, 82, 79),
    collectionWindow: {
      startHour: 6,
      startMinute: 15,
      endHour: 10,
      endMinute: 15,
      label: "Dalle 06:15 alle 10:15 — umidità costante nel fosso",
    },
  },
  {
    id: "taburno-cima-porcino",
    name: "Taburno — Cima Camposauro",
    region: "taburno",
    lat: 41.0689,
    lng: 14.6623,
    altitude: 1165,
    exposure: "north",
    forestType: "Faggeta fitta d'altura",
    species: ["porcino"],
    rainHistory: generateRainHistory(21),
    baseSoilMoisture: 83,
    nightThermalShock: 14.5,
    parkingLat: 41.0718,
    parkingLng: 14.6654,
    hourlyForecasts: generateHourlyForecasts(11, 86, 83),
    collectionWindow: {
      startHour: 5,
      startMinute: 30,
      endHour: 9,
      endMinute: 0,
      label: "Dalle 05:30 alle 09:00 — shock termico notturno >14°C",
    },
  },
  {
    id: "sannio-pietrelcina",
    name: "Sannio — Bosco di Pietrelcina",
    region: "sannio",
    lat: 41.0612,
    lng: 14.5289,
    altitude: 680,
    exposure: "east",
    forestType: "Castagneto con sottobosco di Quercia",
    species: ["estatino", "galletto"],
    rainHistory: generateRainHistory(10),
    baseSoilMoisture: 65,
    nightThermalShock: 9.8,
    parkingLat: 41.0589,
    parkingLng: 14.5234,
    hourlyForecasts: generateHourlyForecasts(17, 72, 65),
    collectionWindow: {
      startHour: 5,
      startMinute: 45,
      endHour: 9,
      endMinute: 15,
      label: "Dalle 05:45 alle 09:15 — radura esposta a Est",
    },
  },
  {
    id: "molise-matese-lago",
    name: "Molise — Versante Lago del Matese",
    region: "molise",
    lat: 41.3389,
    lng: 14.4012,
    altitude: 1010,
    exposure: "north",
    forestType: "Faggeta con zone umide lacustri",
    species: ["porcino", "galletto"],
    rainHistory: generateRainHistory(17),
    baseSoilMoisture: 82,
    nightThermalShock: 13.2,
    parkingLat: 41.3356,
    parkingLng: 14.3978,
    hourlyForecasts: generateHourlyForecasts(12, 84, 82),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 0,
      label: "Dalle 06:00 alle 10:00 — umidità dal lago e faggeta",
    },
  },
  {
    id: "campania-partenio",
    name: "Campania — Massiccio del Partenio",
    region: "campania",
    lat: 41.0123,
    lng: 14.7123,
    altitude: 1120,
    exposure: "north",
    forestType: "Faggeta fitta con Faggio e Acero",
    species: ["porcino", "estatino"],
    rainHistory: generateRainHistory(19),
    baseSoilMoisture: 80,
    nightThermalShock: 13.8,
    parkingLat: 41.0089,
    parkingLng: 14.7056,
    hourlyForecasts: generateHourlyForecasts(11, 85, 80),
    collectionWindow: {
      startHour: 5,
      startMinute: 30,
      endHour: 9,
      endMinute: 30,
      label: "Dalle 05:30 alle 09:30 — quota >1100m, escursione termica forte",
    },
  },
  {
    id: "sannio-telese",
    name: "Sannio — Bosco di Telese Terme",
    region: "sannio",
    lat: 41.2289,
    lng: 14.5289,
    altitude: 620,
    exposure: "east",
    forestType: "Castagneto con Quercia e sottobosco umido",
    species: ["estatino", "galletto"],
    rainHistory: generateRainHistory(13),
    baseSoilMoisture: 67,
    nightThermalShock: 10.2,
    parkingLat: 41.2256,
    parkingLng: 14.5234,
    hourlyForecasts: generateHourlyForecasts(16, 73, 67),
    collectionWindow: {
      startHour: 5,
      startMinute: 30,
      endHour: 9,
      endMinute: 0,
      label: "Dalle 05:30 alle 09:00 — vicino a Benevento, sole mattutino Est",
    },
  },
  {
    id: "sannio-foce-sannita",
    name: "Sannio — Foce Sannita / Cerreto",
    region: "sannio",
    lat: 41.3389,
    lng: 14.5623,
    altitude: 710,
    exposure: "north",
    forestType: "Faggeta giovane con fossi muschiosi",
    species: ["galletto", "estatino"],
    rainHistory: generateRainHistory(17),
    baseSoilMoisture: 75,
    nightThermalShock: 10.8,
    parkingLat: 41.3345,
    parkingLng: 14.5567,
    hourlyForecasts: generateHourlyForecasts(14, 79, 75),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 0,
      label: "Dalle 06:00 alle 10:00 — umidità nei valloni del Fortore",
    },
  },
  {
    id: "sannio-cerreto",
    name: "Sannio — Bosco di Cerreto Sannita",
    region: "sannio",
    lat: 41.3456,
    lng: 14.5712,
    altitude: 580,
    exposure: "east",
    forestType: "Castagneto e Querceto termofilo",
    species: ["estatino", "galletto"],
    rainHistory: generateRainHistory(12),
    baseSoilMoisture: 64,
    nightThermalShock: 9.5,
    parkingLat: 41.3423,
    parkingLng: 14.5678,
    hourlyForecasts: generateHourlyForecasts(17, 71, 64),
    collectionWindow: {
      startHour: 5,
      startMinute: 45,
      endHour: 9,
      endMinute: 15,
      label: "Dalle 05:45 alle 09:15 — a 50 min da Benevento",
    },
  },
  {
    id: "sannio-pietraroja",
    name: "Sannio — Bosco di Pietraroja",
    region: "sannio",
    lat: 41.3123,
    lng: 14.6789,
    altitude: 890,
    exposure: "north",
    forestType: "Faggeta con zone umide e muschi",
    species: ["galletto", "porcino"],
    rainHistory: generateRainHistory(19),
    baseSoilMoisture: 77,
    nightThermalShock: 12.2,
    parkingLat: 41.3089,
    parkingLng: 14.6723,
    hourlyForecasts: generateHourlyForecasts(12, 81, 77),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 0,
      label: "Dalle 06:00 alle 10:00 — Appennino sannitico",
    },
  },
  {
    id: "molise-trivento",
    name: "Molise — Boschi di Trivento",
    region: "molise",
    lat: 41.7689,
    lng: 14.5389,
    altitude: 540,
    exposure: "east",
    forestType: "Querceto e Castagneto collinare",
    species: ["estatino", "galletto"],
    rainHistory: generateRainHistory(11),
    baseSoilMoisture: 63,
    nightThermalShock: 9.2,
    parkingLat: 41.7656,
    parkingLng: 14.5345,
    hourlyForecasts: generateHourlyForecasts(17, 70, 63),
    collectionWindow: {
      startHour: 5,
      startMinute: 30,
      endHour: 9,
      endMinute: 0,
      label: "Dalle 05:30 alle 09:00 — colli a 1h da Benevento",
    },
  },
  {
    id: "molise-bojano",
    name: "Molise — Vallone di Bojano",
    region: "molise",
    lat: 41.4823,
    lng: 14.4723,
    altitude: 680,
    exposure: "north",
    forestType: "Fosso umido con Castagno e Faggio",
    species: ["galletto", "estatino"],
    rainHistory: generateRainHistory(16),
    baseSoilMoisture: 74,
    nightThermalShock: 10.5,
    parkingLat: 41.4789,
    parkingLng: 14.4678,
    hourlyForecasts: generateHourlyForecasts(14, 78, 74),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 0,
      label: "Dalle 06:00 alle 10:00 — versante umido del Biferno",
    },
  },
  {
    id: "molise-colle-anchise",
    name: "Molise — Colle d'Anchise",
    region: "molise",
    lat: 41.5123,
    lng: 14.5523,
    altitude: 820,
    exposure: "north",
    forestType: "Faggeta mista con muschi",
    species: ["galletto", "porcino"],
    rainHistory: generateRainHistory(18),
    baseSoilMoisture: 76,
    nightThermalShock: 11.8,
    parkingLat: 41.5089,
    parkingLng: 14.5478,
    hourlyForecasts: generateHourlyForecasts(13, 80, 76),
    collectionWindow: {
      startHour: 5,
      startMinute: 45,
      endHour: 9,
      endMinute: 30,
      label: "Dalle 05:45 alle 09:30 — rilievi tra Benevento e Campobasso",
    },
  },
  {
    id: "molise-campobasso",
    name: "Molise — Monti di Campobasso",
    region: "molise",
    lat: 41.5623,
    lng: 14.6523,
    altitude: 780,
    exposure: "east",
    forestType: "Castagneto con sottobosco di Quercia",
    species: ["estatino", "galletto"],
    rainHistory: generateRainHistory(14),
    baseSoilMoisture: 69,
    nightThermalShock: 10.5,
    parkingLat: 41.5589,
    parkingLng: 14.6478,
    hourlyForecasts: generateHourlyForecasts(15, 75, 69),
    collectionWindow: {
      startHour: 5,
      startMinute: 30,
      endHour: 9,
      endMinute: 0,
      label: "Dalle 05:30 alle 09:00 — entro 1h 15min da Benevento",
    },
  },
  {
    id: "campania-laceno",
    name: "Irpinia — Laceno / Montella",
    region: "campania",
    lat: 40.9789,
    lng: 15.1289,
    altitude: 950,
    exposure: "north",
    forestType: "Faggeta con fossi e muschi d'altura",
    species: ["porcino", "galletto"],
    rainHistory: generateRainHistory(20),
    baseSoilMoisture: 79,
    nightThermalShock: 12.8,
    parkingLat: 40.9745,
    parkingLng: 15.1234,
    hourlyForecasts: generateHourlyForecasts(12, 82, 79),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 0,
      label: "Dalle 06:00 alle 10:00 — faggeta dell'Alto Cervialto",
    },
  },
  {
    id: "campania-summonte",
    name: "Irpinia — Summonte / Partenio Sud",
    region: "campania",
    lat: 40.9489,
    lng: 14.7423,
    altitude: 870,
    exposure: "north",
    forestType: "Faggeta e Castagneto misto",
    species: ["galletto", "estatino"],
    rainHistory: generateRainHistory(15),
    baseSoilMoisture: 72,
    nightThermalShock: 11.2,
    parkingLat: 40.9456,
    parkingLng: 14.7378,
    hourlyForecasts: generateHourlyForecasts(14, 77, 72),
    collectionWindow: {
      startHour: 5,
      startMinute: 45,
      endHour: 9,
      endMinute: 30,
      label: "Dalle 05:45 alle 09:30 — versante Partenio meridionale",
    },
  },
  {
    id: "campania-cervati",
    name: "Cilento — Monte Cervati",
    region: "campania",
    lat: 40.4123,
    lng: 15.3789,
    altitude: 1280,
    exposure: "north",
    forestType: "Faggeta fitta d'altura",
    species: ["porcino"],
    rainHistory: generateRainHistory(22),
    baseSoilMoisture: 82,
    nightThermalShock: 14.5,
    parkingLat: 40.4089,
    parkingLng: 15.3723,
    hourlyForecasts: generateHourlyForecasts(10, 85, 82),
    collectionWindow: {
      startHour: 5,
      startMinute: 30,
      endHour: 9,
      endMinute: 30,
      label: "Dalle 05:30 alle 09:30 — cima del Cilento interno",
    },
  },
  {
    id: "basilicata-pollino-san-severino",
    name: "Pollino — Boschi di San Severino Lucano",
    region: "basilicata",
    lat: 40.0234,
    lng: 16.1456,
    altitude: 1050,
    exposure: "east",
    forestType: "Castagneto e Querceto con fossi umidi",
    species: ["galletto", "estatino"],
    rainHistory: generateRainHistory(18),
    baseSoilMoisture: 76,
    nightThermalShock: 11.8,
    parkingLat: 40.0189,
    parkingLng: 16.1389,
    hourlyForecasts: generateHourlyForecasts(13, 80, 76),
    collectionWindow: {
      startHour: 5,
      startMinute: 45,
      endHour: 9,
      endMinute: 15,
      label: "Dalle 05:45 alle 09:15 — Finferli su versante Est",
    },
  },
  {
    id: "basilicata-gallipoli-cognato",
    name: "Gallipoli Cognato — Parco delle Dolomiti Lucane",
    region: "basilicata",
    lat: 40.6234,
    lng: 16.1345,
    altitude: 920,
    exposure: "north",
    forestType: "Faggeta con fossi muschiosi e Acero",
    species: ["galletto", "estatino"],
    rainHistory: generateRainHistory(16),
    baseSoilMoisture: 74,
    nightThermalShock: 10.5,
    parkingLat: 40.6189,
    parkingLng: 16.1289,
    hourlyForecasts: generateHourlyForecasts(14, 78, 74),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 0,
      label: "Dalle 06:00 alle 10:00 — ombra fitta nei valloni",
    },
  },
  {
    id: "basilicata-vulture",
    name: "Monte Vulture — Anello dei Laghi",
    region: "basilicata",
    lat: 40.9234,
    lng: 15.6123,
    altitude: 780,
    exposure: "east",
    forestType: "Faggeta mista con Castagno e Quercia",
    species: ["estatino", "galletto"],
    rainHistory: generateRainHistory(14),
    baseSoilMoisture: 70,
    nightThermalShock: 11.2,
    parkingLat: 40.9189,
    parkingLng: 15.6056,
    hourlyForecasts: generateHourlyForecasts(15, 75, 70),
    collectionWindow: {
      startHour: 5,
      startMinute: 30,
      endHour: 8,
      endMinute: 45,
      label: "Dalle 05:30 alle 08:45 — primo sole su boschi del Vulture",
    },
  },
  {
    id: "basilicata-monticchio",
    name: "Appennino Lucano — Laghi di Monticchio",
    region: "basilicata",
    lat: 40.8345,
    lng: 15.6234,
    altitude: 1080,
    exposure: "north",
    forestType: "Faggeta umida con zone lacustri",
    species: ["porcino", "galletto"],
    rainHistory: generateRainHistory(20),
    baseSoilMoisture: 83,
    nightThermalShock: 13.5,
    parkingLat: 40.8298,
    parkingLng: 15.6178,
    hourlyForecasts: generateHourlyForecasts(11, 84, 83),
    collectionWindow: {
      startHour: 5,
      startMinute: 45,
      endHour: 9,
      endMinute: 30,
      label: "Dalle 05:45 alle 09:30 — umidità dai laghi vulcanici",
    },
  },
  {
    id: "basilicata-lagonegrese",
    name: "Lagonegrese — Bosco di San Luca",
    region: "basilicata",
    lat: 40.1234,
    lng: 15.7789,
    altitude: 1150,
    exposure: "north",
    forestType: "Faggeta fitta d'altura",
    species: ["porcino"],
    rainHistory: generateRainHistory(21),
    baseSoilMoisture: 81,
    nightThermalShock: 14.0,
    parkingLat: 40.1189,
    parkingLng: 15.7723,
    hourlyForecasts: generateHourlyForecasts(10, 85, 81),
    collectionWindow: {
      startHour: 6,
      startMinute: 0,
      endHour: 10,
      endMinute: 0,
      label: "Dalle 06:00 alle 10:00 — faggeta fresca del Lagonegrese",
    },
  },
];

export const FUNGAL_ZONES: FungalZone[] = RAW_FUNGAL_ZONES.map((zone) => {
  const driveMinutesFromBenevento =
    DRIVE_FROM_BENEVENTO[zone.id] ?? MAX_DRIVE_MINUTES_FROM_BENEVENTO + 1;
  return {
    ...zone,
    driveMinutesFromBenevento,
    kmFromBenevento: driveMinutesToKm(driveMinutesFromBenevento),
  };
}).filter(
  (zone) =>
    zone.driveMinutesFromBenevento <= MAX_DRIVE_MINUTES_FROM_BENEVENTO
);

assertZonesValid(FUNGAL_ZONES);

export const MAP_CENTER = { lat: BENEVENTO.lat, lng: BENEVENTO.lng };
export const MAP_DEFAULT_ZOOM = 9;

export { BENEVENTO, MAX_DRIVE_MINUTES_FROM_BENEVENTO };
