/**
 * Catalogo fonti — SOLO URL verificati manualmente (2026-06-22).
 * Nessuna voce inventata: niente "Gruppo Micologico X" con link generico AMB.
 * La certificazione runtime è calcolata da sourceCertificationEngine.ts
 */
import type { CertifiedSource } from "./sourceTypes";
import { YOUTUBE_SOURCE_ENTRIES } from "./youtubeSources";

const IT = "Italia";

export const SOURCE_REGISTRY: CertifiedSource[] = [
  // ── NORMATIVA ──
  {
    id: "legge-352-93",
    name: "Legge 14 novembre 1993, n. 352 — Raccolta e commercializzazione funghi",
    shortName: "Legge 352/93",
    category: "normativa",
    url: "https://www.gazzettaufficiale.it/",
    country: IT,
    description: "Quadro nazionale raccolta funghi epigei spontanei.",
    certificationNote: "Gazzetta Ufficiale della Repubblica Italiana",
    topics: ["raccolta", "nazionale"],
  },
  {
    id: "dpr-376-95",
    name: "D.P.R. 376/1995 — Regolamento attuazione Legge 352/93",
    shortName: "DPR 376/95",
    category: "normativa",
    url: "https://www.gazzettaufficiale.it/",
    country: IT,
    description: "Regolamento raccolta, confezionamento e vendita funghi.",
    certificationNote: "Gazzetta Ufficiale",
    topics: ["raccolta", "vendita"],
  },
  {
    id: "campania-lr-funghi",
    name: "Regione Campania — Funghi e tartufi",
    shortName: "Campania L.R. 8/2007",
    category: "normativa",
    url: "https://funghietartufi.regione.campania.it/",
    region: "Campania",
    country: IT,
    description: "Portale ufficiale funghi e tartufi Campania — normativa e tesserini.",
    certificationNote: "Portale istituzionale Regione Campania",
    topics: ["Campania", "normativa", "tesserino"],
  },

  // ── SANITÀ ──
  {
    id: "ministero-salute",
    name: "Ministero della Salute",
    shortName: "Min. Salute",
    category: "sanita",
    url: "https://www.salute.gov.it/",
    country: IT,
    description: "Sicurezza alimentare, micologi, registri nazionali.",
    certificationNote: "Ministero della Repubblica",
    topics: ["sanita", "micologo"],
  },
  {
    id: "iss",
    name: "Istituto Superiore di Sanità (ISS)",
    shortName: "ISS",
    category: "sanita",
    url: "https://www.iss.it/",
    country: IT,
    description: "Tossicologia, sorveglianza avvelenamenti da funghi.",
    certificationNote: "Ente pubblico ricerca sanitaria",
    topics: ["tossicologia", "avvelenamento"],
  },
  {
    id: "iss-cav",
    name: "ISS — Centri Antiveleni (CAV)",
    shortName: "ISS CAV",
    category: "sanita",
    url: "https://www.iss.it/",
    country: IT,
    description: "Rete centri antiveleni — sezione ISS ufficiale (CAV).",
    certificationNote: "ISS — servizio antiveleni nazionale",
    topics: ["emergenza", "avvelenamento", "CAV"],
  },
  {
    id: "asl-benevento",
    name: "ASL Benevento — Servizio prevenzione",
    shortName: "ASL Benevento",
    category: "sanita",
    url: "https://www.aslbenevento.it/",
    region: "Sannio",
    country: IT,
    description: "Controllo obbligatorio funghi raccolti — Sannio.",
    certificationNote: "Azienda Sanitaria Locale ufficiale",
    topics: ["Sannio", "identificazione", "Benevento"],
  },
  {
    id: "asl-caserta",
    name: "ASL Caserta",
    shortName: "ASL Caserta",
    category: "sanita",
    url: "https://www.aslcaserta.it/",
    region: "Campania",
    country: IT,
    description: "Servizi prevenzione e controllo funghi ASL Caserta.",
    certificationNote: "ASL ufficiale",
    topics: ["Campania", "identificazione"],
  },
  {
    id: "asp-basilicata",
    name: "ASP Basilicata",
    shortName: "ASP Basilicata",
    category: "sanita",
    url: "https://www.aspbasilicata.it/",
    region: "Basilicata",
    country: IT,
    description: "Azienda Sanitaria Provinciale Basilicata.",
    certificationNote: "ASP ufficiale",
    topics: ["Basilicata", "identificazione"],
  },
  {
    id: "asrem-molise",
    name: "ASReM — Azienda Sanitaria Regionale Molise",
    shortName: "ASReM",
    category: "sanita",
    url: "https://www.asrem.molise.it/",
    region: "Molise",
    country: IT,
    description: "Sanità regionale Molise — controllo funghi.",
    certificationNote: "ASReM ufficiale",
    topics: ["Molise", "identificazione"],
  },

  // ── REGIONI (Sud operativo) ──
  {
    id: "regione-molise",
    name: "Regione Molise",
    shortName: "Regione Molise",
    category: "normativa",
    url: "https://www.regione.molise.it/",
    region: "Molise",
    country: IT,
    description: "Portale istituzionale Regione Molise.",
    certificationNote: "Regione ufficiale",
    topics: ["Molise"],
  },
  {
    id: "regione-basilicata",
    name: "Regione Basilicata",
    shortName: "Regione Basilicata",
    category: "normativa",
    url: "https://www.regione.basilicata.it/",
    region: "Basilicata",
    country: IT,
    description: "Portale istituzionale Regione Basilicata.",
    certificationNote: "Regione ufficiale",
    topics: ["Basilicata"],
  },
  {
    id: "regione-campania",
    name: "Regione Campania",
    shortName: "Regione Campania",
    category: "normativa",
    url: "https://www.regione.campania.it/",
    region: "Campania",
    country: IT,
    description: "Portale istituzionale Regione Campania.",
    certificationNote: "Regione ufficiale",
    topics: ["Campania"],
  },

  // ── ARPA / AMBIENTE ──
  {
    id: "ispra",
    name: "ISPRA — Istituto Superiore Protezione Ambiente",
    shortName: "ISPRA",
    category: "ambiente",
    url: "https://www.isprambiente.gov.it/",
    country: IT,
    description: "Dati ambientali e biodiversità nazionale.",
    certificationNote: "Ente pubblico ambientale",
    topics: ["ambiente", "biodiversità"],
  },
  {
    id: "arpa-campania",
    name: "ARPA Campania",
    shortName: "ARPA Campania",
    category: "meteo",
    url: "https://www.arpacampania.it/",
    region: "Campania",
    country: IT,
    description: "Agenzia regionale protezione ambientale Campania — meteo/agrometeo.",
    certificationNote: "ARPA ufficiale",
    topics: ["meteo", "Campania", "agrometeo"],
  },
  {
    id: "arpa-molise",
    name: "ARPA Molise",
    shortName: "ARPA Molise",
    category: "meteo",
    url: "https://www.arpamolise.it/",
    region: "Molise",
    country: IT,
    description: "Meteo e dati ambientali Molise.",
    certificationNote: "ARPA ufficiale",
    topics: ["meteo", "Molise"],
  },
  {
    id: "arpa-basilicata",
    name: "ARPA Basilicata",
    shortName: "ARPA Basilicata",
    category: "meteo",
    url: "https://www.arpab.it/",
    region: "Basilicata",
    country: IT,
    description: "Meteo e ambiente Basilicata.",
    certificationNote: "ARPA ufficiale (arpab.it)",
    topics: ["meteo", "Basilicata"],
  },
  {
    id: "crea",
    name: "CREA — Consiglio per la ricerca in agricoltura",
    shortName: "CREA",
    category: "ambiente",
    url: "https://www.crea.gov.it/",
    country: IT,
    description: "Ricerca agricola e forestale.",
    certificationNote: "Ente pubblico ricerca",
    topics: ["agrometeo", "foreste"],
  },
  {
    id: "igm",
    name: "IGM — Istituto Geografico Militare",
    shortName: "IGM",
    category: "ambiente",
    url: "https://www.igmi.org/",
    country: IT,
    description: "Cartografia ufficiale quote e toponimi.",
    certificationNote: "Ente cartografico militare",
    topics: ["cartografia", "quote"],
  },

  // ── METEO ──
  {
    id: "dpc",
    name: "Protezione Civile — Allerta meteo",
    shortName: "Protezione Civile",
    category: "meteo",
    url: "https://www.protezionecivile.gov.it/",
    country: IT,
    description: "Allerta meteo-idrogeologica nazionale.",
    certificationNote: "Dipartimento Protezione Civile",
    topics: ["allerta", "meteo"],
  },
  {
    id: "meteo-am",
    name: "Meteo Aeronautica Militare",
    shortName: "Meteo AM",
    category: "meteo",
    url: "https://www.meteoam.it/",
    country: IT,
    description: "Previsioni meteo ufficiali AM.",
    certificationNote: "Aeronautica Militare",
    topics: ["meteo", "previsioni"],
  },
  {
    id: "open-meteo",
    name: "Open-Meteo (ECMWF/GFS/ICON)",
    shortName: "Open-Meteo",
    category: "meteo",
    url: "https://open-meteo.com/",
    country: "Internazionale",
    description: "API meteo usata da MushroomRadar per Sprout Score.",
    certificationNote: "Dati da modelli meteorologici istituzionali",
    topics: ["meteo", "API"],
  },
  {
    id: "ecmwf",
    name: "ECMWF",
    shortName: "ECMWF",
    category: "meteo",
    url: "https://www.ecmwf.int/",
    country: "UE",
    description: "Centro europeo previsioni medio raggio.",
    certificationNote: "Centro intergovernativo",
    topics: ["meteo", "modello"],
  },

  // ── PARCHI (Sud — zone Radar) ──
  {
    id: "parco-taburno",
    name: "Ente Parco Regionale Taburno Camposauro",
    shortName: "Parco Taburno",
    category: "parco",
    url: "https://enteparcotaburnocamposauro.it/",
    region: "Campania",
    country: IT,
    description: "Regolamento raccolta nel parco taburnino.",
    certificationNote: "Ente parco regionale ufficiale",
    topics: ["Taburno", "parco", "raccolta"],
  },
  {
    id: "cm-taburno",
    name: "Comunità Montana del Taburno",
    shortName: "CM Taburno",
    category: "parco",
    url: "https://comunitamontanataburno.it/",
    region: "Campania",
    country: IT,
    description: "Tesserini e regolamenti raccolta funghi area Taburno.",
    certificationNote: "Ente montano pubblico",
    topics: ["Taburno", "tesserino", "Benevento"],
  },
  {
    id: "parco-matese",
    name: "Ente Parco Regionale del Matese",
    shortName: "Parco Matese",
    category: "parco",
    url: "https://www.parcomatese.it/",
    region: "Campania",
    country: IT,
    description: "Regolamentazione raccolta nel Matese.",
    certificationNote: "Ente parco regionale",
    topics: ["Matese", "parco", "raccolta"],
  },
  {
    id: "parco-pollino",
    name: "Parco Nazionale del Pollino",
    shortName: "Parco Pollino",
    category: "parco",
    url: "https://www.parcopollino.it/",
    region: "Basilicata",
    country: IT,
    description: "Regolamento raccolta nel Pollino.",
    certificationNote: "Parco nazionale ufficiale",
    topics: ["Pollino", "parco", "raccolta"],
  },
  {
    id: "parco-cilento",
    name: "Parco Nazionale del Cilento",
    shortName: "Parco Cilento",
    category: "parco",
    url: "https://www.cilentoediano.it/",
    region: "Campania",
    country: IT,
    description: "Norme raccolta funghi nel Cilento.",
    certificationNote: "Parco nazionale UNESCO",
    topics: ["Cilento", "parco", "raccolta"],
  },
  {
    id: "parco-gargano",
    name: "Parco Nazionale del Gargano",
    shortName: "Parco Gargano",
    category: "parco",
    url: "https://www.parcogargano.it/",
    region: "Puglia",
    country: IT,
    description: "Regolamento raccolta nel Gargano.",
    certificationNote: "Parco nazionale ufficiale",
    topics: ["Gargano", "parco"],
  },
  {
    id: "parco-abruzzo",
    name: "Parco Nazionale d'Abruzzo, Lazio e Molise",
    shortName: "PNALM",
    category: "parco",
    url: "https://www.parcoabruzzo.it/",
    region: "Molise",
    country: IT,
    description: "Norme raccolta in parco appenninico.",
    certificationNote: "Parco nazionale ufficiale",
    topics: ["Molise", "parco", "Appennino"],
  },

  // ── MICOLOGIA (solo enti reali, URL propri) ──
  {
    id: "amb",
    name: "Associazione Micologica Bresadola (AMB)",
    shortName: "AMB",
    category: "micologia",
    url: "https://www.ambbresadola.it/",
    country: IT,
    description: "Associazione micologica nazionale — riviste e gruppi territoriali.",
    certificationNote: "Associazione storica — elenco gruppi sul sito ufficiale",
    topics: ["identificazione", "formazione"],
  },
  {
    id: "umi",
    name: "Unione Micologica Italiana (UMI) APS",
    shortName: "UMI",
    category: "micologia",
    url: "https://www.unionemicologicaitaliana-aps.it/",
    country: IT,
    description: "Promozione studi micologici dal 1969.",
    certificationNote: "APS riconosciuta",
    topics: ["micologia", "convegni"],
  },
  {
    id: "cnr",
    name: "CNR — Consiglio Nazionale delle Ricerche",
    shortName: "CNR",
    category: "micologia",
    url: "https://www.cnr.it/",
    country: IT,
    description: "Ricerca botanica e biologia dei funghi.",
    certificationNote: "Ente pubblico ricerca",
    topics: ["ricerca", "micologia"],
  },
  {
    id: "uni-napoli",
    name: "Università Federico II — Napoli",
    shortName: "UniNA",
    category: "micologia",
    url: "https://www.unina.it/",
    region: "Campania",
    country: IT,
    description: "Ricerca forestale Sud Italia.",
    certificationNote: "Università statale",
    topics: ["Campania", "forestale"],
  },
  {
    id: "uni-molise",
    name: "Università del Molise",
    shortName: "UniMol",
    category: "micologia",
    url: "https://www.unimol.it/",
    region: "Molise",
    country: IT,
    description: "Ecosistemi forestali Matese-Molise.",
    certificationNote: "Università statale",
    topics: ["Molise", "Matese"],
  },
  {
    id: "uni-basilicata",
    name: "Università della Basilicata",
    shortName: "UniBas",
    category: "micologia",
    url: "https://www.unibas.it/",
    region: "Basilicata",
    country: IT,
    description: "Studi boschi appenninici e Pollino.",
    certificationNote: "Università statale",
    topics: ["Basilicata", "Pollino"],
  },

  // ── EDITORIALE ──
  {
    id: "funghimagazine",
    name: "Funghimagazine.it",
    shortName: "Funghimagazine",
    category: "editoriale",
    url: "https://funghimagazine.it/",
    country: IT,
    description: "Meteofunghi, tabelle nascite, calendario porcini.",
    certificationNote: "Editoriale specialistico — non istituzionale",
    topics: ["porcini", "meteo", "nascite"],
  },
  {
    id: "fm-tabelle",
    name: "Funghimagazine — Tabelle nascite funghi",
    shortName: "FM Tabelle",
    category: "editoriale",
    url: "https://funghimagazine.it/tabelle-nascite-funghi/",
    country: IT,
    description: "Semaforo/tabelle regionali nascite.",
    certificationNote: "Sezione editoriale Funghimagazine",
    topics: ["nascite", "regioni"],
  },
  {
    id: "fm-estatino",
    name: "Funghimagazine — Porcino estatino (B. aestivalis)",
    shortName: "FM Estatino",
    category: "editoriale",
    url: "https://funghimagazine.it/boletus-reticulatus-o-aestivalis-porcino-estatino/",
    country: IT,
    description: "Scheda specie porcino estivo.",
    certificationNote: "Scheda editoriale Funghimagazine",
    topics: ["estatino", "habitat"],
  },
  {
    id: "fm-calendario",
    name: "Funghimagazine — Calendario porcini primavera-estate",
    shortName: "FM Calendario",
    category: "editoriale",
    url: "https://funghimagazine.it/fm-calendario-porcini-primavera-estate/",
    country: IT,
    description: "Fenologia porcini per zone e quote.",
    certificationNote: "Calendario editoriale Funghimagazine",
    topics: ["porcini", "stagionalità"],
  },

  // ── INTERNAZIONALE ──
  {
    id: "efsa",
    name: "EFSA — Autorità europea sicurezza alimentare",
    shortName: "EFSA",
    category: "internazionale",
    url: "https://www.efsa.europa.eu/",
    country: "UE",
    description: "Sicurezza alimentare UE.",
    certificationNote: "Agenzia UE ufficiale",
    topics: ["sicurezza", "UE"],
  },
  {
    id: "index-fungorum",
    name: "Index Fungorum — Nomenclatura ufficiale",
    shortName: "Index Fungorum",
    category: "internazionale",
    url: "https://www.indexfungorum.org/",
    country: "Internazionale",
    description: "Database nomenclatura taxonomica funghi.",
    certificationNote: "Registro nomenclaturale internazionale",
    topics: ["tassonomia"],
  },
  {
    id: "mycobank",
    name: "MycoBank",
    shortName: "MycoBank",
    category: "internazionale",
    url: "https://mycobank.org/",
    country: "Internazionale",
    description: "Registro taxonomico funghi (CBS-KNAW).",
    certificationNote: "Registro internazionale CBS",
    topics: ["tassonomia"],
  },

  // ── GEOCODING ──
  {
    id: "nominatim",
    name: "OpenStreetMap Nominatim",
    shortName: "Nominatim",
    category: "ambiente",
    url: "https://nominatim.openstreetmap.org/",
    country: "Internazionale",
    description: "Geocodifica luoghi per origine utente.",
    certificationNote: "OpenStreetMap Foundation",
    topics: ["geocoding"],
  },

  // ── YOUTUBE (solo video/canali verificati — vedi youtubeSources.ts) ──
  ...(YOUTUBE_SOURCE_ENTRIES as CertifiedSource[]),
];
